package ru.krymer.delivery.ui.screens.shop.models

import android.content.Context
import ru.krymer.delivery.data.model.ClientModel
import ru.krymer.delivery.data.model.ProductModel
import ru.krymer.delivery.data.model.RequestModel
import ru.krymer.delivery.data.model.ShopModel
import ru.krymer.delivery.data.model.utilModel.TypePayModel

sealed class ShopEvent {
    data class ChangeArrear(val arrear: String): ShopEvent()
    data class ChangeDept(val dept: String): ShopEvent()
    data class ChangeAdd(val add: String): ShopEvent()
    data object ShowAddDialogShopCurrentRoute : ShopEvent()
    data object ShowAddDialogShopAllRoutes : ShopEvent()
    data class ChangeCountBonusProduct(val bonus: String, val product: ProductModel) : ShopEvent()
    data class ChangeCountProduct(val count: String, val product: ProductModel) : ShopEvent()
    data class ChangeCountExchange(val exchange: String, val product: ProductModel) : ShopEvent()
    data object OnAdminManaged: ShopEvent()
    data object DismissAddDialog : ShopEvent()
    data object ShopAddAction : ShopEvent()
    data class ShowDeleteDialog(val shop: ShopModel) : ShopEvent()
    data object DismissDeleteDialog : ShopEvent()
    data object DeleteAction : ShopEvent()
    data class OpenRequest(val shop: ShopModel) : ShopEvent()
    data object ShopActionInvoked : ShopEvent()
    data class OpenGeoPoint(val context: Context, val cord: String) : ShopEvent()
    data object DismissSelectorClientInAddDialog : ShopEvent()
    data object ShowSelectorClientInAddDialog : ShopEvent()
    data class DropDownSelectClient(val shop: ClientModel) : ShopEvent()
    data object OpenMillageDialog : ShopEvent()
    data object MillageSaveAction : ShopEvent()
    data object DismissRequestDialog : ShopEvent()
    data object InitSaveRequestDialog : ShopEvent()
    data object ShowRequestsInfoDialog : ShopEvent()
    data object DismissRequestInfoDialog : ShopEvent()
    data object SaveArrears : ShopEvent()
    data class ValueChangeCash(val money: String) : ShopEvent()
    data class ValueChangeNoCashMoney(val money: String) : ShopEvent()
    data object RequestSaveAction : ShopEvent()
    data object ShowDialogChangeArrears : ShopEvent()
    data class ChangeArrears(val arrears: String) : ShopEvent()
    data class ValueChangeMillage(val millage: String) : ShopEvent()
    data object SaveAddSum : ShopEvent()
    data object OpenAddSumDialog : ShopEvent()
    data object UpdateInfo : ShopEvent()
    data object SetArrearsInField : ShopEvent()
    data object SetOrderInField : ShopEvent()
    data object SetOrderAndArrearsSumInField : ShopEvent()
    data object SetArrearsAndAddInField : ShopEvent()
    data object SetOrderAndAddInField : ShopEvent()
    data object SetAddInField : ShopEvent()
    data object SetOrderAndArrearsAndAddSumInField : ShopEvent()
    data class ChangeAddSum(val addSum: String) : ShopEvent()
    data object DismissAddSumDialog : ShopEvent()
    data object DismissMillageDialog : ShopEvent()
    data object DismissDialogChangeArrears : ShopEvent()
    data object ShowChangeTypePayDialog : ShopEvent()
    data class ChangeTypePay(val type: TypePayModel) : ShopEvent()
    data object DismissChangeTypePayDialog : ShopEvent()
    data class ChangeDropDownStateTypePayChanger(val state: Boolean) : ShopEvent()
    data class ChangeCountRequest(val count: String, val item: RequestModel) : ShopEvent()
    data class ChangeExchangeRequest(val exchange: String, val item: RequestModel) : ShopEvent()
    data class ChangeBonusRequest(val bonus: String, val item: RequestModel) : ShopEvent()
    data class DeleteRequest(val request: RequestModel) : ShopEvent()
    data object DismissConfirmRequestDialog : ShopEvent()

    data class OpenInfoShopDialog(val shop: ShopModel) : ShopEvent()
    data object DismissInfoShopDialog : ShopEvent()
    data object DismissInfoBlockDialog : ShopEvent()

    data object ShowDialogAddRequest : ShopEvent()
    data object DismissDialogAddRequest : ShopEvent()
    data object RequestAddAction : ShopEvent()
    data object SwitchPrice : ShopEvent()
    data class CopyInfoData(val context: Context) : ShopEvent()
}