package ru.krymer.delivery.ui.screens.shop.models

import android.content.Context
import ru.krymer.delivery.data.model.ClientModel
import ru.krymer.delivery.data.model.MessageModel
import ru.krymer.delivery.data.model.ProductModel
import ru.krymer.delivery.data.model.RequestModel
import ru.krymer.delivery.data.model.ShopModel

sealed class ShopEvent {
    data class ChangeArrear(val arrear: String): ShopEvent()
    data class ChangeDept(val dept: String): ShopEvent()
    data class ChangeAdd(val add: String): ShopEvent()
    data object ShowAddDialogShopCurrentRoute : ShopEvent()
    data object ShowAddDialogShopAllRoutes : ShopEvent()
    data class ChangeCountBonusProduct(val bonus: String, val product: ProductModel) : ShopEvent()
    data class ChangeCountProduct(val count: String, val product: ProductModel) : ShopEvent()
    data object DismissAddDialog : ShopEvent()
    data object ShopAddAction : ShopEvent()
    data object ShowDeleteDialog: ShopEvent()
    data object DismissDeleteDialog : ShopEvent()
    data object DeleteShop : ShopEvent()
    data class OpenRequest(val shop: ShopModel) : ShopEvent()
    data object ShopActionInvoked : ShopEvent()
    data class OpenGeoPoint(val context: Context, val cord: String) : ShopEvent()
    data object DismissSelectorClientInAddDialog : ShopEvent()
    data object ShowSelectorClientInAddDialog : ShopEvent()
    data class DropDownSelectClient(val shop: ClientModel) : ShopEvent()
    data object OpenMillageDialog : ShopEvent()
    data object MillageSaveAction : ShopEvent()
    data object DismissRequestDialog : ShopEvent()
    data object InitSaveRequestDialog : ShopEvent()
    data object ShowRequestsInfoDialog : ShopEvent()
    data object DismissRequestInfoDialog : ShopEvent()
    data object SaveArrears : ShopEvent()
    data class ValueChangeCash(val money: String) : ShopEvent()
    data class ValueChangeNoCashMoney(val money: String) : ShopEvent()
    data object RequestSaveAction : ShopEvent()
    data object ShowDialogChangeArrears : ShopEvent()
    data class ChangeArrears(val arrears: String) : ShopEvent()
    data class ValueChangeMillage(val millage: String) : ShopEvent()
    data object SaveAddSum : ShopEvent()
    data object OpenAddSumDialog : ShopEvent()
    data object UpdateInfo : ShopEvent()
    data class SetArrearsInField(val arrears: Double) : ShopEvent()
    data object SetOrderInField : ShopEvent()
    data class SetOrderAndArrearsSumInField(val arrears: Double) : ShopEvent()
    data class SetArrearsAndAddInField(val sum: Double) : ShopEvent()
    data class SetOrderAndAddInField(val addSum: Double) : ShopEvent()
    data class SetAddInField(val addSum: Double) : ShopEvent()
    data class SetOrderAndArrearsAndAddSumInField(val arrears: Double, val addSum: Double) : ShopEvent()
    data class ChangeAddSum(val addSum: String) : ShopEvent()
    data object DismissAddSumDialog : ShopEvent()
    data object DismissMillageDialog : ShopEvent()
    data object DismissDialogChangeArrears : ShopEvent()
    data object ChangeTypePay : ShopEvent()
    data class ChangeDropDownStateTypePayChanger(val state: Boolean) : ShopEvent()
    data class ChangeCountRequest(val count: String, val item: RequestModel) : ShopEvent()
    data class ChangeExchangeRequest(val exchange: String, val item: RequestModel) : ShopEvent()
    data class ChangeBonusRequest(val bonus: String, val item: RequestModel) : ShopEvent()
    data object DismissConfirmRequestDialog : ShopEvent()

    data class OpenInfoShopDialog(val shop: ShopModel) : ShopEvent()
    data object DismissInfoShopDialog : ShopEvent()

    data object ShowDialogAddRequest : ShopEvent()
    data object DismissDialogAddRequest : ShopEvent()
    data object RequestAddAction : ShopEvent()
    data object SwitchPrice : ShopEvent()
    data object SwitchBonus: ShopEvent()

    data class CopyInfoData(val context: Context) : ShopEvent()

    data class ChangeAddStatusProduct(val product: ProductModel) : ShopEvent()
    data object ToggleMessageDialog: ShopEvent()
    data object SendMessage: ShopEvent()
    data class ChangeMessage(val message: String): ShopEvent()
    data class DeleteMessage(val message: MessageModel): ShopEvent()
    data object SwitchBonusState: ShopEvent()
    data object ShowHideDialogAnalitic: ShopEvent()
    data object CopyAndSaveShop : ShopEvent()
    data class ToggleLogsShopDialog(val shop: ShopModel?): ShopEvent()
    data object ChangeStateIsCopyDialog : ShopEvent()
    data class SelectShop(val shop: ShopModel) : ShopEvent()
}